spring.application.name=lowfare-calendar
management.endpoint.health.show-details=always


######### REDIS configuration ######
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
management.health.redis.enabled=false

######### PUBSUB configuration ######
spring.cloud.gcp.pubsub.enabled=true
spring.cloud.gcp.project-id=local
spring.cloud.gcp.pubsub.emulator-host=${PUBSUB_EMULATOR_HOST:localhost:8085}


#Circuit Breaker configuration
resilience4j.circuitbreaker.instances.providerA.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.providerA.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.providerA.sliding-window-size=5